name: Koi
options:
  bundleIdPrefix: com.gariasf
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.2.1"
    CURRENT_PROJECT_VERSION: "6"
    DEVELOPMENT_LANGUAGE: en
    DEVELOPMENT_TEAM: AB72ZGY444
    CODE_SIGN_STYLE: Automatic
targets:
  Koi:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Koi
        excludes:
          - "Resources/Info.plist"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gariasf.koi
        PRODUCT_NAME: Koi
        INFOPLIST_FILE: Koi/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: icon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1"
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
  KoiTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Tests
    dependencies:
      - target: Koi
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gariasf.koi.tests
        GENERATE_INFOPLIST_FILE: YES
  KoiUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: UITests
    dependencies:
      - target: Koi
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gariasf.koi.uitests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: Koi
schemes:
  Koi:
    build:
      targets:
        Koi: all
        KoiTests: [test]
        KoiUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - KoiTests
        - KoiUITests
